import { Hono } from "hono";
import { zValidator } from "@hono/zod-validator";
import { eq } from "drizzle-orm";
import type { Env, AppVariables } from "../env";
import { domains, auditLogs } from "../db/schema";
import { generateId } from "../lib/id";
import { requireAuth } from "../middleware/auth";
import { createDomainSchema, updateDomainSchema } from "@shared/types";

const domainsRouter = new Hono<{ Bindings: Env; Variables: AppVariables }>();

// All domain routes require authentication
domainsRouter.use("/*", requireAuth);

/**
 * GET /api/domains
 * List all domains.
 */
domainsRouter.get("/", async (c) => {
  const db = c.get("db");
  const result = await db.select().from(domains).orderBy(domains.createdAt);
  return c.json({ data: result });
});

/**
 * POST /api/domains
 * Add a new domain.
 */
domainsRouter.post(
  "/",
  zValidator("json", createDomainSchema, (result, c) => {
    if (!result.success) {
      return c.json(
        { error: "Validation failed", details: result.error.flatten() },
        400,
      );
    }
  }),
  async (c) => {
    const db = c.get("db");
    const { domain } = c.req.valid("json");

    // Check for duplicate
    const existing = await db
      .select()
      .from(domains)
      .where(eq(domains.domain, domain))
      .limit(1)
      .then((rows) => rows[0]);

    if (existing) {
      return c.json({ error: "Domain already exists" }, 409);
    }

    const id = generateId();
    await db.insert(domains).values({
      id,
      domain,
      status: "pending",
      mxVerified: false,
    });

    // Audit log
    await db.insert(auditLogs).values({
      id: generateId(),
      userId: c.get("userId"),
      action: "domain.create",
      resourceType: "domain",
      resourceId: id,
      details: JSON.stringify({ domain }),
    });

    const created = await db
      .select()
      .from(domains)
      .where(eq(domains.id, id))
      .limit(1)
      .then((rows) => rows[0]);

    return c.json({ data: created, message: "Domain created successfully" }, 201);
  },
);

/**
 * GET /api/domains/:id
 * Get domain details including DNS configuration instructions.
 */
domainsRouter.get("/:id", async (c) => {
  const db = c.get("db");
  const { id } = c.req.param();

  const domain = await db
    .select()
    .from(domains)
    .where(eq(domains.id, id))
    .limit(1)
    .then((rows) => rows[0]);

  if (!domain) {
    return c.json({ error: "Domain not found" }, 404);
  }

  // Include DNS setup instructions
  const dnsInstructions = {
    mx: [
      { type: "MX", name: domain.domain, content: "route1.mx.cloudflare.net", priority: 36 },
      { type: "MX", name: domain.domain, content: "route2.mx.cloudflare.net", priority: 84 },
      { type: "MX", name: domain.domain, content: "route3.mx.cloudflare.net", priority: 12 },
    ],
    spf: {
      type: "TXT",
      name: domain.domain,
      content: "v=spf1 include:_spf.mx.cloudflare.net ~all",
      note: "Required for email authentication",
    },
    dkim: {
      note: "DKIM record is auto-generated by Cloudflare Email Routing. Check CF Dashboard → Email → Email Routing for the required TXT record.",
    },
  };

  return c.json({ data: { ...domain, dnsInstructions } });
});

/**
 * PATCH /api/domains/:id
 * Update domain (enable/disable).
 */
domainsRouter.patch(
  "/:id",
  zValidator("json", updateDomainSchema, (result, c) => {
    if (!result.success) {
      return c.json(
        { error: "Validation failed", details: result.error.flatten() },
        400,
      );
    }
  }),
  async (c) => {
    const db = c.get("db");
    const { id } = c.req.param();
    const updates = c.req.valid("json");

    const existing = await db
      .select()
      .from(domains)
      .where(eq(domains.id, id))
      .limit(1)
      .then((rows) => rows[0]);

    if (!existing) {
      return c.json({ error: "Domain not found" }, 404);
    }

    await db
      .update(domains)
      .set({ ...updates, updatedAt: new Date().toISOString() })
      .where(eq(domains.id, id));

    // Audit log
    await db.insert(auditLogs).values({
      id: generateId(),
      userId: c.get("userId"),
      action: "domain.update",
      resourceType: "domain",
      resourceId: id,
      details: JSON.stringify(updates),
    });

    const updated = await db
      .select()
      .from(domains)
      .where(eq(domains.id, id))
      .limit(1)
      .then((rows) => rows[0]);

    return c.json({ data: updated, message: "Domain updated successfully" });
  },
);

/**
 * DELETE /api/domains/:id
 * Remove a domain and all associated mailboxes/aliases/groups (cascade).
 */
domainsRouter.delete("/:id", async (c) => {
  const db = c.get("db");
  const { id } = c.req.param();

  const existing = await db
    .select()
    .from(domains)
    .where(eq(domains.id, id))
    .limit(1)
    .then((rows) => rows[0]);

  if (!existing) {
    return c.json({ error: "Domain not found" }, 404);
  }

  await db.delete(domains).where(eq(domains.id, id));

  // Audit log
  await db.insert(auditLogs).values({
    id: generateId(),
    userId: c.get("userId"),
    action: "domain.delete",
    resourceType: "domain",
    resourceId: id,
    details: JSON.stringify({ domain: existing.domain }),
  });

  return c.json({ message: "Domain deleted successfully" });
});

/**
 * POST /api/domains/:id/verify
 * Verify domain MX records via Cloudflare DNS-over-HTTPS.
 * Checks that at least one MX record points to Cloudflare Email Routing.
 */
domainsRouter.post("/:id/verify", async (c) => {
  const db = c.get("db");
  const { id } = c.req.param();

  const domain = await db
    .select()
    .from(domains)
    .where(eq(domains.id, id))
    .limit(1)
    .then((rows) => rows[0]);

  if (!domain) {
    return c.json({ error: "Domain not found" }, 404);
  }

  // Query MX records via Cloudflare DNS-over-HTTPS
  const CLOUDFLARE_MX_HOSTS = [
    "route1.mx.cloudflare.net",
    "route2.mx.cloudflare.net",
    "route3.mx.cloudflare.net",
  ];

  try {
    const dnsRes = await fetch(
      `https://cloudflare-dns.com/dns-query?name=${encodeURIComponent(domain.domain)}&type=MX`,
      { headers: { Accept: "application/dns-json" } },
    );

    if (!dnsRes.ok) {
      return c.json(
        { error: "DNS lookup failed, please try again later" },
        502,
      );
    }

    const dnsData = (await dnsRes.json()) as {
      Status: number;
      Answer?: Array<{ type: number; data: string }>;
    };

    // MX answers have type 15; data format is "priority host."
    const mxRecords = (dnsData.Answer ?? [])
      .filter((r) => r.type === 15)
      .map((r) => {
        // data looks like "69 route1.mx.cloudflare.net."
        const parts = r.data.split(" ");
        return (parts[1] ?? "").replace(/\.$/, "").toLowerCase();
      });

    const hasCloudflare = mxRecords.some((host) =>
      CLOUDFLARE_MX_HOSTS.includes(host),
    );

    if (!hasCloudflare) {
      return c.json(
        {
          error: "MX verification failed",
          details: {
            found: mxRecords.length > 0 ? mxRecords : ["(no MX records)"],
            expected: CLOUDFLARE_MX_HOSTS,
            hint: "Add MX records pointing to route1/route2/route3.mx.cloudflare.net in your DNS settings, then try again.",
          },
        },
        422,
      );
    }
  } catch (err) {
    console.error("[EdgeMail] DNS lookup error:", err);
    return c.json({ error: "DNS lookup failed due to a network error" }, 502);
  }

  // MX verified — activate domain
  await db
    .update(domains)
    .set({
      mxVerified: true,
      status: "active",
      updatedAt: new Date().toISOString(),
    })
    .where(eq(domains.id, id));

  // Audit log
  await db.insert(auditLogs).values({
    id: generateId(),
    userId: c.get("userId"),
    action: "domain.verify",
    resourceType: "domain",
    resourceId: id,
  });

  return c.json({
    data: { mxVerified: true, status: "active" },
    message: "Domain verified and activated",
  });
});

export default domainsRouter;
